export * from './pages/create-inventory-product-page';
export * from './pages/edit-inventory-product-page';
export * from './pages/inventory-categories-page';
export * from './pages/inventory-kardex-page';
export * from './pages/inventory-movements-page';
export * from './pages/inventory-product-detail-page';
export * from './pages/inventory-products-page';
export * from './pages/inventory-stock-page';
export * from './pages/inventory-warehouses-page';
